branches:
  only:
    - master

language: python
python:
  - "2.7"

install:
  - pip install pylint_runner
  - pylint_runner -v . || true

before_script:
  - pip install nose
  - pip install coverage
  - pip install nosexcover
#  - python setup.py install
#  - python setup.py test
  - nosetests -s ./tests/

script:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      pip install -U sphinx
      git checkout -b gh-pages
      sphinx-apidoc -o ./sphinx/rst/ ./p2ee/
      sphinx-build -b html ./sphinx/rst/ ./sphinx/html/
      cp -R ./sphinx/html/* .
      git config --global user.name "ghpages"
      git config --global user.email "ghpages@moengage.com"
      git add .
      git commit -am "generating documentation"
      git push -u -f https://$user:$user_token@github.com/moengage/p2ee.git/ gh-pages
    fi
